[test]
levels = ["syntax", "install", "registration", "instantiation", "execution"]
publish = true

[test.workflows]
timeout = 300
cpu = ['rigged_mesh_manipulation']
gpu = ['multiple_masks_depthcorrected','multiple_masks','rigging','workflow']

[test.platforms]
linux = true
macos = true
windows = true
windows_portable = true
linux_gpu = true
windows_gpu = true
windows_portable_gpu = true
