# Copyright (c) 2025 Andrea Pozzetti
# SPDX-License-Identifier: MIT
"""
ComfyUI SAM 3D Body Custom Nodes

Aggregate all node class mappings from submodules.
"""

from .processing.load_model import (
    NODE_CLASS_MAPPINGS as LOAD_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LOAD_DISPLAY_MAPPINGS,
)
from .processing.process import (
    NODE_CLASS_MAPPINGS as PROCESS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROCESS_DISPLAY_MAPPINGS,
)
from .processing.export_rigged import (
    NODE_CLASS_MAPPINGS as EXPORT_RIGGED_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as EXPORT_RIGGED_DISPLAY_MAPPINGS,
)
from .processing.export_animated import (
    NODE_CLASS_MAPPINGS as EXPORT_ANIMATED_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as EXPORT_ANIMATED_DISPLAY_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(LOAD_MAPPINGS)
NODE_CLASS_MAPPINGS.update(PROCESS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(EXPORT_RIGGED_MAPPINGS)
NODE_CLASS_MAPPINGS.update(EXPORT_ANIMATED_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(LOAD_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(PROCESS_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(EXPORT_RIGGED_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(EXPORT_ANIMATED_DISPLAY_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
